settings:
  username: "NAMATOVU-CHRISTINE"
  commit_msg: "âš¡ Update recent activity"
  max_lines: 5
  readme_file: "./README.md"
  disabled_events:
    - "comments"
  url_text: "{REPO}{ID}"
  messages:
    comments: "ğŸ’¬ Commented on {ID} in {REPO}"
    issue_opened: "â— Opened issue {ID} in {REPO}"
    issue_closed: "âœ”ï¸ Closed issue {ID} in {REPO}"
    pr_opened: "ğŸ”€ Opened PR {ID} in {REPO}"
    pr_merged: "ğŸ‰ Merged PR {ID} in {REPO}"
    pr_closed: "âŒ Closed PR {ID} in {REPO}"
    created_repo: "ğŸ“¦ Created new repository {REPO}"
    starred_repo: "â­ Starred {REPO}"
    forked_repo: "ğŸ”± Forked {REPO}"
